services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - database:/app/data

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  database: